[workspace]
resolver = "2"
members = [
    "cordis-rust",
    "cordis-spine",
    "cordis-tui",
    "cordis-gateway",
    "cordis-app",
    "cordis-render/markdown",
    "cordis-render/mermaid",
    "vendor/mermaid/ordered_hashmap",
    "vendor/mermaid/graphlib_rust",
    "vendor/mermaid/dagre_rust",
    "vendor/mermaid/mermaid-to-svg",
    "vendor/xai/fuzzy-file-search",
    "vendor/xai/workflow",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
