//! Lean per-scope `MEMORY.md` index (title + relative path summaries).
//!
//! Generated after remember/flush/dream and on [`crate::layout::MemoryRoot::ensure_layout`].
//! Budget mirrors Grok `V2ManifestBudget` (8 KiB / 64 entries).
//! Indexes `topics/` + `observations/_inbox/` (plus flat `observations/*.md` read-compat).
//! Read-only for tools/model; shown by `memory_get` / `/memory`.

use std::io::Read;
use std::path::{Path, PathBuf};

use crate::layout::{MemoryRoot, MemoryScope, ScopePaths};

const MAX_MANIFEST_BYTES: usize = 8 * 1024;
const MAX_MANIFEST_ENTRIES: usize = 64;
const MAX_DESCRIPTION_BYTES: usize = 160;
const MAX_SOURCE_BYTES: u64 = 8 * 1024;

#[derive(Debug, Clone)]
pub struct Manifest {
    pub content: String,
    pub included_entries: usize,
}

/// Manifest size budget (Grok `V2ManifestBudget` without the v2 name).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ManifestBudget {
    pub max_bytes: usize,
    pub max_entries: usize,
    pub max_description_bytes: usize,
}

impl Default for ManifestBudget {
    fn default() -> Self {
        Self {
            max_bytes: MAX_MANIFEST_BYTES,
            max_entries: MAX_MANIFEST_ENTRIES,
            max_description_bytes: MAX_DESCRIPTION_BYTES,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum EntryKind {
    Topic,
    Observation,
}

#[derive(Debug, Clone)]
struct Entry {
    kind: EntryKind,
    relative_path: String,
    title: String,
    description: String,
    modified: Option<std::time::SystemTime>,
}

/// Regenerate `MEMORY.md` for both global and workspace scopes.
pub fn refresh_all(root: &MemoryRoot) -> std::io::Result<()> {
    regenerate_scope(&root.global, MemoryScope::Global)?;
    regenerate_scope(&root.workspace, MemoryScope::Workspace)?;
    Ok(())
}

/// Rebuild one scope's `MEMORY.md` with an atomic replace.
pub fn regenerate_scope(scope: &ScopePaths, which: MemoryScope) -> std::io::Result<Manifest> {
    let manifest = render_scope(&scope.root, which)?;
    persist_replacing(&scope.root.join("MEMORY.md"), manifest.content.as_bytes())?;
    Ok(manifest)
}

/// Path to a scope's generated index.
pub fn memory_md_path(scope: &ScopePaths) -> PathBuf {
    scope.root.join("MEMORY.md")
}

/// Read a scope's `MEMORY.md`, truncated to `max_chars` (char count).
/// Returns `(body, truncated)`. Missing file → `None`.
pub fn read_manifest_body(scope: &ScopePaths, max_chars: usize) -> Option<(String, bool)> {
    let path = memory_md_path(scope);
    let text = std::fs::read_to_string(&path).ok()?;
    let truncated = text.chars().count() > max_chars;
    let body: String = text.chars().take(max_chars).collect();
    Some((body, truncated))
}

fn render_scope(scope_dir: &Path, which: MemoryScope) -> std::io::Result<Manifest> {
    let mut entries = Vec::new();
    collect_entries(
        scope_dir,
        Path::new("topics"),
        EntryKind::Topic,
        &mut entries,
    )?;
    // Canonical inbox; also flat observations/*.md for read-compat pre-migrate.
    collect_entries(
        scope_dir,
        Path::new("observations/_inbox"),
        EntryKind::Observation,
        &mut entries,
    )?;
    collect_flat_observation_entries(scope_dir, &mut entries)?;

    entries.sort_by(|left, right| {
        left.kind.cmp(&right.kind).then_with(|| match left.kind {
            EntryKind::Topic => left.relative_path.cmp(&right.relative_path),
            EntryKind::Observation => right
                .modified
                .cmp(&left.modified)
                .then_with(|| right.relative_path.cmp(&left.relative_path)),
        })
    });

    let heading = match which {
        MemoryScope::Global => "Global memory",
        MemoryScope::Workspace => "Workspace memory",
    };
    let header = format!(
        "# {heading}\n\n> Generated by Dock. Do not edit this file directly.\n> Paths are relative to `{}`.\n",
        sanitize_inline(&scope_dir.display().to_string())
    );

    if entries.is_empty() {
        let content = format!("{header}\nNo memory files have been recorded yet.\n");
        return Ok(Manifest {
            content: truncate_bytes(&content, MAX_MANIFEST_BYTES),
            included_entries: 0,
        });
    }

    let mut content = header;
    let mut current_kind = None;
    let mut included = 0;
    for entry in entries.into_iter().take(MAX_MANIFEST_ENTRIES) {
        let mut addition = String::new();
        if current_kind != Some(entry.kind) {
            addition.push_str(match entry.kind {
                EntryKind::Topic => "\n## Topics\n",
                EntryKind::Observation => "\n## Pending observations\n",
            });
        }
        addition.push_str("\n- **");
        addition.push_str(&entry.title);
        addition.push_str("**");
        if entry.kind == EntryKind::Topic && !entry.description.is_empty() {
            addition.push_str(" — ");
            addition.push_str(&entry.description);
        }
        addition.push_str(" (`");
        addition.push_str(&entry.relative_path);
        addition.push_str("`)\n");
        if content.len().saturating_add(addition.len()) > MAX_MANIFEST_BYTES {
            if entry.kind == EntryKind::Observation {
                break;
            }
            continue;
        }
        content.push_str(&addition);
        current_kind = Some(entry.kind);
        included += 1;
    }

    Ok(Manifest {
        content,
        included_entries: included,
    })
}

fn collect_entries(
    scope_dir: &Path,
    relative_dir: &Path,
    kind: EntryKind,
    entries: &mut Vec<Entry>,
) -> std::io::Result<()> {
    let directory = scope_dir.join(relative_dir);
    let read_dir = match std::fs::read_dir(&directory) {
        Ok(rd) => rd,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(e),
    };
    let mut candidates = Vec::new();
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Nested folders under observations/ (e.g. archive) — skip non-md trees lightly.
            if kind == EntryKind::Observation {
                continue;
            }
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let relative = match path.strip_prefix(scope_dir) {
            Ok(rel) => rel.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };
        let modified = entry.metadata().and_then(|m| m.modified()).ok();
        candidates.push((relative, path, modified));
    }
    candidates.sort_by(|a, b| a.0.cmp(&b.0));
    for (relative_path, path, modified) in candidates {
        let (title, description) = summarize_file(&path).unwrap_or_else(|_| {
            let title = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("memory")
                .to_owned();
            (title, String::new())
        });
        entries.push(Entry {
            kind,
            relative_path: sanitize_inline(&relative_path),
            title: sanitize_inline(&truncate_chars(&title, MAX_DESCRIPTION_BYTES)),
            description: sanitize_inline(&description),
            modified,
        });
    }
    Ok(())
}


/// Immediate `.md` children of `observations/` (not `_inbox` / archive / nested).
fn collect_flat_observation_entries(
    scope_dir: &Path,
    entries: &mut Vec<Entry>,
) -> std::io::Result<()> {
    let directory = scope_dir.join("observations");
    let read_dir = match std::fs::read_dir(&directory) {
        Ok(rd) => rd,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(e),
    };
    let mut candidates = Vec::new();
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let relative = match path.strip_prefix(scope_dir) {
            Ok(rel) => rel.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };
        // Skip if already listed via _inbox (same basename after migrate race).
        if entries.iter().any(|e| e.relative_path == relative.replace('\\', "/")) {
            continue;
        }
        let modified = entry.metadata().and_then(|m| m.modified()).ok();
        candidates.push((relative, path, modified));
    }
    candidates.sort_by(|a, b| a.0.cmp(&b.0));
    for (relative_path, path, modified) in candidates {
        let (title, description) = summarize_file(&path).unwrap_or_else(|_| {
            let title = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("memory")
                .to_owned();
            (title, String::new())
        });
        entries.push(Entry {
            kind: EntryKind::Observation,
            relative_path: sanitize_inline(&relative_path),
            title: sanitize_inline(&truncate_chars(&title, MAX_DESCRIPTION_BYTES)),
            description: sanitize_inline(&description),
            modified,
        });
    }
    Ok(())
}

fn summarize_file(path: &Path) -> std::io::Result<(String, String)> {
    let mut file = std::fs::File::open(path)?;
    let mut bytes = Vec::new();
    std::io::Read::by_ref(&mut file)
        .take(MAX_SOURCE_BYTES)
        .read_to_end(&mut bytes)?;
    let body = String::from_utf8_lossy(&bytes);
    let mut title = None;
    let mut description = None;
    for line in body.lines().map(str::trim).filter(|l| !l.is_empty()) {
        if title.is_none() && line.starts_with('#') {
            let heading = line.trim_start_matches('#').trim();
            if !heading.is_empty() {
                title = Some(heading.to_owned());
            }
            continue;
        }
        if description.is_none()
            && !line.starts_with('#')
            && !line.starts_with("<!--")
            && !line.starts_with('>')
        {
            description = Some(truncate_chars(line, MAX_DESCRIPTION_BYTES));
        }
        if title.is_some() && description.is_some() {
            break;
        }
    }
    let fallback = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("memory")
        .to_owned();
    Ok((title.unwrap_or(fallback), description.unwrap_or_default()))
}

fn sanitize_inline(value: &str) -> String {
    value
        .chars()
        .map(|c| match c {
            '\n' | '\r' => ' ',
            '`' => '\'',
            _ => c,
        })
        .collect()
}

fn truncate_chars(s: &str, max: usize) -> String {
    let mut out: String = s.chars().take(max).collect();
    if s.chars().count() > max {
        out.push('…');
    }
    out
}

fn truncate_bytes(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_owned();
    }
    let mut end = max;
    while end > 0 && !s.is_char_boundary(end) {
        end -= 1;
    }
    let mut out = s[..end].to_owned();
    out.push('…');
    out
}

fn persist_replacing(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut tmp = tempfile::Builder::new()
        .prefix(".memory-md-")
        .suffix(".tmp")
        .tempfile_in(path.parent().unwrap_or_else(|| Path::new(".")))?;
    use std::io::Write;
    tmp.write_all(bytes)?;
    tmp.as_file().sync_all()?;
    tmp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::MemoryRoot;

    #[test]
    fn refresh_writes_index_with_topics() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/manifest-proj"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("ownership.md"),
            "# Ownership\n\nPrefer explicit ownership transfer.\n",
        )
        .unwrap();
        refresh_all(&root).unwrap();
        let md = std::fs::read_to_string(root.workspace.root.join("MEMORY.md")).unwrap();
        assert!(md.contains("Workspace memory"));
        assert!(md.contains("Ownership"));
        assert!(md.contains("topics/ownership.md"));
        let global = std::fs::read_to_string(root.global.root.join("MEMORY.md")).unwrap();
        assert!(global.contains("No memory files"));
    }
}
