//! Hybrid search: FTS5 + optional sqlite-vec KNN + temporal decay + source weight + MMR.
//!
//! Graceful degradation: no vec / no query embedding → FTS-only (like Grok).

use std::collections::HashMap;

use crate::chunker;
use crate::config::{MemorySearchConfig, SearchResult};
use crate::index::{MemoryIndex, SearchHit};
use crate::layout::MemoryRoot;
use crate::mmr;

/// Open the index and query. Reindexes once when the DB is missing or empty.
/// Callers that hold a [`crate::MemoryFileWatcher`] should [`sync_dirty_paths`]
/// before search when [`crate::MemoryFileWatcher::is_dirty`].
///
/// If a watcher reports dirty paths, reindex existing files and delete_path missing ones.
pub fn sync_dirty_paths(root: &MemoryRoot, index: &mut MemoryIndex, dirty: &[std::path::PathBuf]) {
    for path in dirty {
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        if path.is_file() {
            let source = root.classify_source(path);
            let _ = index.reindex_file(path, source);
        } else {
            let _ = index.delete_path(path);
        }
    }
}

pub fn search_memory(
    root: &MemoryRoot,
    query: &str,
    max_results: usize,
) -> Result<Vec<SearchHit>, String> {
    let config = MemorySearchConfig {
        max_results: max_results.max(1),
        ..MemorySearchConfig::default()
    };
    search_memory_with_config(root, query, &config, None)
}

pub fn search_memory_with_config(
    root: &MemoryRoot,
    query: &str,
    config: &MemorySearchConfig,
    query_embedding: Option<&[f32]>,
) -> Result<Vec<SearchHit>, String> {
    let db = root.search_db();
    let missing = !db.exists();
    let dims = query_embedding.map(|e| e.len()).unwrap_or(1024);
    let mut index =
        MemoryIndex::open_or_create_with_dimensions(&db, dims).map_err(|e| e.to_string())?;
    if missing || index.is_empty() {
        let _ = index.reindex_tree(root);
    }
    let merge =
        hybrid_search_merge(&index, query, query_embedding, config).map_err(|e| e.to_string())?;
    Ok(merge
        .results
        .into_iter()
        .map(|r| SearchHit {
            path: r.path,
            start_line: r.start_line,
            end_line: r.end_line,
            text: r.snippet,
            source: r.source,
            score: r.score,
        })
        .collect())
}

pub struct SearchMerge {
    pub results: Vec<SearchResult>,
    pub is_vector_degraded: bool,
}

fn is_evergreen_source(source: &str) -> bool {
    matches!(source, "global" | "workspace")
}

fn is_content_free(text: &str, source: &str) -> bool {
    is_structurally_empty(text) || (is_evergreen_source(source) && is_scaffold_stub(text))
}

fn is_scaffold_stub(text: &str) -> bool {
    let lower = text.to_lowercase();
    lower.contains("generated by dock")
        || lower.contains("do not edit this file directly")
        || lower.contains("no memory files have been recorded yet")
}

fn is_structurally_empty(text: &str) -> bool {
    if !text.contains("<!--") {
        return lines_are_scaffolding(text);
    }
    let mut without_comments = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find("<!--") {
        match rest.get(start + 4..).and_then(|s| s.find("-->")) {
            Some(end) => {
                if let Some(prefix) = rest.get(..start) {
                    without_comments.push_str(prefix);
                }
                let after = start + 4 + end + 3;
                rest = rest.get(after..).unwrap_or("");
            }
            None => {
                without_comments.push_str(rest);
                rest = "";
                break;
            }
        }
    }
    without_comments.push_str(rest);
    lines_are_scaffolding(&without_comments)
}

fn lines_are_scaffolding(text: &str) -> bool {
    for line in text.lines() {
        if line.trim().is_empty() {
            continue;
        }
        if chunker::header_level(line).is_some() {
            continue;
        }
        return false;
    }
    true
}

fn temporal_decay_multiplier(
    source: &str,
    created_at: i64,
    now_secs: i64,
    half_life_days: Option<f64>,
) -> f64 {
    let Some(half_life) = half_life_days.filter(|h| *h > 0.0) else {
        return 1.0;
    };
    if is_evergreen_source(source) {
        return 1.0;
    }
    let age_days = ((now_secs - created_at).max(0) as f64) / 86_400.0;
    let lambda = std::f64::consts::LN_2 / half_life;
    (-lambda * age_days).exp()
}

/// Floor applied when searching without a query embedding.
///
/// FTS ranks are min-max normalized into [0, 1], so a lone weak BM25 hit can
/// land at ~1.0. Raising the FTS-only gate toward Grok's 0.7 avoids relying on
/// that lift alone; hybrid (vec) paths keep `config.min_score`.
const FTS_ONLY_MIN_SCORE: f64 = 0.7;

/// Sync merge: FTS (+ optional vector) → normalize → decay → source weight → MMR.
pub fn hybrid_search_merge(
    index: &MemoryIndex,
    query: &str,
    query_embedding: Option<&[f32]>,
    config: &MemorySearchConfig,
) -> Result<SearchMerge, Box<dyn std::error::Error>> {
    let candidate_limit = config.max_results.saturating_mul(3).max(1);
    let effective_min_score = if query_embedding.is_none() {
        (config.min_score as f64).max(FTS_ONLY_MIN_SCORE)
    } else {
        config.min_score as f64
    };

    let mut fts_results = index.search_fts(query, candidate_limit).unwrap_or_default();
    let evergreen = index
        .search_fts_by_sources(query, candidate_limit, &["global", "workspace"])
        .unwrap_or_default();
    let existing: std::collections::HashSet<String> =
        fts_results.iter().map(|r| r.chunk_id.clone()).collect();
    for r in evergreen {
        if !existing.contains(&r.chunk_id) {
            fts_results.push(r);
        }
    }

    let (vec_results, is_vector_degraded) =
        if let Some(embedding) = query_embedding.filter(|_| index.vec_available()) {
            match index.vector_search(embedding, candidate_limit) {
                Ok(results) => (results, false),
                Err(error) => {
                    tracing::warn!(%error, "vector search failed");
                    (vec![], true)
                }
            }
        } else {
            (vec![], false)
        };

    let mut fts_scores: HashMap<String, f64> = HashMap::new();
    let mut vec_scores: HashMap<String, f64> = HashMap::new();

    if !fts_results.is_empty() {
        let min_rank = fts_results
            .iter()
            .map(|r| r.rank)
            .fold(f64::INFINITY, f64::min);
        let max_rank = fts_results
            .iter()
            .map(|r| r.rank)
            .fold(f64::NEG_INFINITY, f64::max);
        let range = (max_rank - min_rank).max(f64::EPSILON);
        for r in &fts_results {
            let normalized = 1.0 - (r.rank - min_rank) / range;
            fts_scores.insert(r.chunk_id.clone(), normalized);
        }
    }

    const MAX_L2_DISTANCE: f64 = 2.0;
    for (chunk_id, distance) in &vec_results {
        let similarity = (1.0 - (*distance / MAX_L2_DISTANCE)).clamp(0.0, 1.0);
        vec_scores.insert(chunk_id.clone(), similarity);
    }

    let mut scores: HashMap<String, f64> = HashMap::new();
    let text_weight = config.text_weight as f64;
    let vector_weight = config.vector_weight as f64;
    let all_chunk_ids: std::collections::HashSet<&String> =
        fts_scores.keys().chain(vec_scores.keys()).collect();

    for chunk_id in all_chunk_ids {
        let fts = fts_scores.get(chunk_id).copied().unwrap_or(0.0);
        let vec = vec_scores.get(chunk_id).copied().unwrap_or(0.0);
        let score = if fts > 0.0 && vec > 0.0 {
            (text_weight * fts + vector_weight * vec).max(fts)
        } else if fts > 0.0 {
            fts
        } else {
            vector_weight * vec
        };
        scores.insert(chunk_id.clone(), score);
    }

    let now_secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64;
    let half_life = config.effective_half_life_days();

    let mut ranked: Vec<(f64, SearchResult)> = Vec::new();
    for (chunk_id, base_score) in &scores {
        let Some(chunk) = index.get_chunk(chunk_id).ok().flatten() else {
            continue;
        };
        if is_content_free(&chunk.text, &chunk.source) {
            continue;
        }
        let decay_multiplier =
            temporal_decay_multiplier(&chunk.source, chunk.created_at, now_secs, half_life);
        let source_weight = config
            .source_weights
            .get(&chunk.source)
            .copied()
            .unwrap_or(1.0) as f64;
        let access_boost = 1.0 + (chunk.access_count as f64).ln_1p() * 0.05;
        let raw_score = base_score * decay_multiplier * source_weight * access_boost;
        let display_score = raw_score.clamp(0.0, 1.0);
        if display_score >= effective_min_score {
            ranked.push((
                raw_score,
                SearchResult {
                    chunk_id: chunk_id.clone(),
                    path: chunk.path.clone(),
                    start_line: chunk.start_line,
                    end_line: chunk.end_line,
                    score: display_score,
                    snippet: chunk.text.clone(),
                    source: chunk.source.clone(),
                    created_at: chunk.created_at,
                },
            ));
        }
    }

    ranked.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));

    let mmr_enabled = config.mmr.enabled;
    let mut relevance: Vec<f64> = if mmr_enabled {
        Vec::with_capacity(ranked.len())
    } else {
        Vec::new()
    };
    let mut results: Vec<SearchResult> = Vec::with_capacity(ranked.len());
    for (raw_score, result) in ranked {
        if mmr_enabled {
            relevance.push(raw_score);
        }
        results.push(result);
    }

    mmr::mmr_rerank(&mut results, &relevance, &config.mmr);
    results.truncate(config.max_results);

    Ok(SearchMerge {
        results,
        is_vector_degraded,
    })
}

pub fn format_search_results(hits: &[SearchHit]) -> String {
    if hits.is_empty() {
        return "No memory results found for query.".into();
    }
    let mut out = format!("Found {} memory result(s):\n", hits.len());
    for (i, hit) in hits.iter().enumerate() {
        out.push_str(&format!(
            "\n### Result {} (score: {:.2}, source: {})\n**File:** {} (lines {}-{})\n```\n{}\n```\n",
            i + 1,
            hit.score,
            hit.source,
            hit.path,
            hit.start_line + 1,
            hit.end_line,
            hit.text
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::index::MemoryIndex;
    use std::path::Path;

    #[test]
    fn hybrid_fts_only_finds_topic() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/hybrid-proj"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("api.md"),
            "## API\n\nREST endpoints use bearer tokens\n",
        )
        .unwrap();
        let hits = search_memory(&root, "bearer tokens", 5).unwrap();
        assert!(!hits.is_empty(), "hits={hits:?}");
        assert!(hits.first().unwrap().text.to_lowercase().contains("bearer"));
    }

    #[tokio::test]
    async fn hybrid_with_mock_embedding() {
        use crate::config::MemorySearchConfig;
        use crate::embedding::{embed_missing_chunks, EmbeddingProvider, MockEmbeddingProvider};

        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/hybrid-vec"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("vec.md"),
            "## Vectors\n\nsemantic search needs embeddings\n",
        )
        .unwrap();
        let mut idx = MemoryIndex::open_or_create_with_dimensions(&root.search_db(), 8).unwrap();
        let _ = idx.reindex_tree(&root);
        if !idx.vec_available() {
            // CI without vec still exercises FTS path via other tests.
            return;
        }
        let provider = MockEmbeddingProvider { dimensions: 8 };
        let n = embed_missing_chunks(&idx, &provider).await;
        assert!(n >= 1, "embedded={n}");
        let q = provider
            .embed_batch(&["semantic embeddings"])
            .await
            .unwrap();
        let cfg = MemorySearchConfig::default();
        let merge =
            hybrid_search_merge(&idx, "semantic embeddings", Some(q.first().unwrap()), &cfg)
                .unwrap();
        assert!(!merge.results.is_empty() || cfg.min_score > 0.9);
    }

    #[test]
    fn dirty_sync_before_search_picks_up_external_edit() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/dirty-sync"));
        root.ensure_layout().unwrap();
        let path = root.workspace.topics.join("ext.md");
        std::fs::write(&path, "## Before\n\nold content about zebras\n").unwrap();
        let mut idx = MemoryIndex::open_or_create(&root.search_db()).unwrap();
        let _ = idx.reindex_tree(&root);
        drop(idx);

        // External edit (as a file watcher would observe).
        std::fs::write(&path, "## After\n\nnew content about platypus secrets\n").unwrap();
        let mut idx = MemoryIndex::open_or_create(&root.search_db()).unwrap();
        sync_dirty_paths(&root, &mut idx, std::slice::from_ref(&path));
        drop(idx);

        let hits = search_memory(&root, "platypus secrets", 5).unwrap();
        assert!(
            hits.iter()
                .any(|h| h.text.to_lowercase().contains("platypus")),
            "dirty sync should reindex external edit; hits={hits:?}"
        );
        let stale = search_memory(&root, "zebras", 5).unwrap();
        assert!(
            !stale
                .iter()
                .any(|h| h.text.to_lowercase().contains("zebras")),
            "old chunk text should be gone after reindex"
        );
    }

    #[tokio::test]
    async fn search_memory_with_config_embedding_path() {
        use crate::embedding::{embed_missing_chunks, EmbeddingProvider, MockEmbeddingProvider};

        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/embed-path"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("emb.md"),
            "## Embed path\n\nquery vectors unlock hybrid recall\n",
        )
        .unwrap();
        let mut idx = MemoryIndex::open_or_create_with_dimensions(&root.search_db(), 8).unwrap();
        let _ = idx.reindex_tree(&root);
        if !idx.vec_available() {
            return;
        }
        let provider = MockEmbeddingProvider { dimensions: 8 };
        assert!(embed_missing_chunks(&idx, &provider).await >= 1);
        let q = provider
            .embed_batch(&["query vectors hybrid"])
            .await
            .unwrap();
        let cfg = MemorySearchConfig {
            min_score: 0.0,
            ..MemorySearchConfig::default()
        };
        let hits = search_memory_with_config(
            &root,
            "query vectors hybrid",
            &cfg,
            Some(q.first().unwrap()),
        )
        .unwrap();
        assert!(
            !hits.is_empty(),
            "embedding path must return hits; got {hits:?}"
        );
    }

    /// Regression: OR-style FTS matched Dock-only notes for "Lynn Dock review style".
    #[test]
    fn fts_only_rejects_partial_term_overlap() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/fts-partial"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("dock.md"),
            "## Dock\n\nDock TUI keyboard shortcuts and session layout.\n",
        )
        .unwrap();
        std::fs::write(
            root.workspace.topics.join("ship.md"),
            "## Shipping\n\nDock release checklist for the memory crate.\n",
        )
        .unwrap();
        let hits = search_memory(&root, "Lynn Dock review style", 5).unwrap();
        assert!(
            hits.is_empty(),
            "Dock-only corpus must not match multi-term query; hits={hits:?}"
        );
    }

    #[test]
    fn fts_only_recalls_when_all_terms_present() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/fts-full"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("lynn-style.md"),
            "## Review\n\nLynn Dock review style: prefer short PRs, cite tip SHA, no merge.\n",
        )
        .unwrap();
        let hits = search_memory(&root, "Lynn Dock review style", 5).unwrap();
        assert!(
            !hits.is_empty(),
            "all-terms note must recall; hits={hits:?}"
        );
        assert!(
            hits.iter().any(|h| h.text.to_lowercase().contains("lynn")),
            "expected Lynn note; hits={hits:?}"
        );
    }

    #[test]
    fn fts_single_keyword_still_hits() {
        let tmp = tempfile::tempdir().unwrap();
        let root = MemoryRoot::open(tmp.path(), Path::new("/tmp/fts-blake3"));
        root.ensure_layout().unwrap();
        std::fs::write(
            root.workspace.topics.join("hash.md"),
            "## Slugs\n\nWorkspace memory slugs use blake3 over the identity string.\n",
        )
        .unwrap();
        let hits = search_memory(&root, "blake3", 5).unwrap();
        assert!(
            !hits.is_empty(),
            "single keyword blake3 must still hit; hits={hits:?}"
        );
        assert!(hits.first().unwrap().text.to_lowercase().contains("blake3"));
    }
}
